# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindows.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.maxAge = 150
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 200, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 270, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 120, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 120, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 72, 15))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 160, 211, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 101, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 200, 211, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 240, 211, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 240, 81, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 280, 211, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 280, 131, 20))
        self.label_5.setObjectName("label_5")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 80, 511, 241))
        self.tableView.setObjectName("tableView")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 380, 211, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 340, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 340, 211, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 380, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 420, 71, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(150, 420, 211, 22))
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.tableView.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.comboBox_2.raise_()
        self.label_3.raise_()
        self.comboBox_3.raise_()
        self.comboBox_4.raise_()
        self.label_4.raise_()
        self.comboBox_5.raise_()
        self.label_5.raise_()
        self.comboBox_6.raise_()
        self.label_6.raise_()
        self.lineEdit.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.comboBox_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.pushButton_3.setText(_translate("MainWindow", "Send"))
        self.comboBox.setCurrentText(_translate("MainWindow", "右半结肠（包括：回盲部、升结肠、横结肠右半）"))
        self.comboBox.setItemText(0, _translate("MainWindow", "右半结肠（包括：回盲部、升结肠、横结肠右半）"))
        self.comboBox.setItemText(1, _translate("MainWindow", "左半结肠（包括：横结肠左半、降结肠、乙状结肠）"))
        self.comboBox.setItemText(2, _translate("MainWindow", "直肠"))
        self.comboBox.setItemText(3, _translate("MainWindow", "全大肠散发"))
        self.label.setText(_translate("MainWindow", "息肉部位："))
        self.label_2.setText(_translate("MainWindow", "内镜表现："))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "有蒂"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "有蒂"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "亚蒂"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "平坦"))
        self.label_3.setText(_translate("MainWindow", "息肉病理诊断："))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "炎性息肉"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "炎性息肉"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "增生性息肉"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "腺癌息肉"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "不典型增生/癌变"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "癌"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "锯齿状腺瘤"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "单个"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "单个"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "多个"))
        self.label_4.setText(_translate("MainWindow", "癌灶个数："))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "高分化"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "高分化"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "中分化"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "低分化"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "未分化"))
        self.label_5.setText(_translate("MainWindow", "病理按分化程度："))
        self.comboBox_6.setCurrentText(_translate("MainWindow", "男"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "女"))
        self.label_6.setText(_translate("MainWindow", "姓 名 ："))
        self.label_7.setText(_translate("MainWindow", "性 别 ："))
        self.label_8.setText(_translate("MainWindow", "年 齡 ："))
        self.comboBox_7.setCurrentText(_translate("MainWindow", "0"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "12"))
        self.comboBox_7.setItemText(13, _translate("MainWindow", "13"))
        self.comboBox_7.setItemText(14, _translate("MainWindow", "14"))
        self.comboBox_7.setItemText(15, _translate("MainWindow", "15"))
        self.comboBox_7.setItemText(16, _translate("MainWindow", "16"))
        self.comboBox_7.setItemText(17, _translate("MainWindow", "17"))
        self.comboBox_7.setItemText(18, _translate("MainWindow", "18"))
        self.comboBox_7.setItemText(19, _translate("MainWindow", "19"))
        self.comboBox_7.setItemText(20, _translate("MainWindow", "20"))

